export { default as Home } from "./home/Home"
export { default as Course } from "./course/Course"
export { default as Courses } from "./courses/Courses"
export { default as Category } from "./category/Category"
export { default as Article } from "./article/Article"
export { default as Login } from "./login/Login"
export { default as Register } from "./register/Register"